name = "agm-worker"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "AGM_DB"
database_id = "bf34313a-4319-41bf-b87c-f62c2cb8c743"

[[kv_namespaces]]
binding = "AUDIT_KV"
id = "8af5a01a018442aa8309c5532d480fc6"

# Set auth secret with: wrangler secret put AGM_SECRET
